# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
# The recipe for this docker image can be found at:
# https://github.com/rust-lang/docker-rust/blob/e7703b2cf525f2525bdf8d131cd66b5b38b1513c/1.31.0/stretch/Dockerfile
image: "rust:1.31.0"

stages:
  - build
  - test

build:cargo:
  stage: build
  artifacts:
    paths:
      - target/
  script:
  - rustc --version && cargo --version
  - cargo build --lib --tests --verbose
  - cargo build --lib --tests --verbose --release

test:cargo:
  stage: test
  dependencies:
  - build:cargo
  script:
  - cargo test --verbose

lint:clippy:
  image: "rust:latest"
  stage: test
  dependencies:
    - build:cargo
  script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings

format:rustfmt:
  image: "rust:latest"
  script:
  - rustup toolchain install nightly -c rustfmt
  - cargo +nightly fmt -- --check

coverage:kcov:
  # Only executed on master because we keep artifacts around forever.
  only:
  - master
  stage: test
  dependencies:
    - build:cargo
  artifacts:
    expire_in: never
    paths:
    - kcov/
  coverage: '/^Coverage+:\s(\d+(?:\.\d+)?)/'
  script:
  - echo 'deb http://deb.debian.org/debian testing main' >> /etc/apt/sources.list
  - echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list
  - apt-get update
  - apt-get install --assume-yes kcov
  - files=$(find target/debug -maxdepth 1 -type f -executable -iname "*-????????????????");
    covs="";
    for file in ${files}; do
      cov="kcov-$(basename ${file})";
      kcov --exclude-pattern=/usr/ --verify "${cov}" "${file}";
      covs+=" ${cov}";
    done;
    kcov --merge kcov/ ${covs};
    COVERAGE=$(grep --only-matching 'covered":"[^"]\+"' kcov/index.js | awk -F'"' '{print $3}');
    echo "Coverage:" ${COVERAGE};
